// package com.bsgated.model;

// import jakarta.persistence.*;
// import lombok.*;
// import java.time.LocalDateTime;
 
// @Entity
// @Table(name = "guest_parking")
// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// @Builder
// public class GuestParking {
 
//     @Id
//     @GeneratedValue(strategy = GenerationType.UUID)
//     private String id;
 
//     // ── Resident info ──────────────────────────────────────────────────────
//     @Column(nullable = false)
//     private String residentId;
 
//     @Column(nullable = false)
//     private String residentName;
 
//     @Column(nullable = false)
//     private String unit;
 
//     // ── Guest info ─────────────────────────────────────────────────────────
//     @Column(nullable = false)
//     private String guestName;
 
//     private String guestPhone;
 
//     // ── Vehicle info ───────────────────────────────────────────────────────
//     @Column(nullable = false)
//     private String vehicleNumber;
 
//     @Column(nullable = false)
//     private String vehicleType;      // Car, Bike, Auto, Truck
 
//     // ── Booking info ───────────────────────────────────────────────────────
//     private String expectedDate;     // free-text date string from resident
 
//     @Column(nullable = false)
//     private Integer durationDays;    // 1 / 2 / 3 / 7
 
//     @Column(nullable = false)
//     private String slotNumber;       // Pre-assigned: "15", "A1", etc.
 
//     @Column(nullable = false, unique = true)
//     private String parkingOtp;       // 6-digit OTP
 
//     // ── Status & timestamps ────────────────────────────────────────────────
//     @Enumerated(EnumType.STRING)
//     @Column(nullable = false)
//     private GuestParkingStatus status;
 
//     @Column(nullable = false, updatable = false)
//     private LocalDateTime requestedAt;
 
//     private LocalDateTime approvedAt;
//     private LocalDateTime rejectedAt;
//     private LocalDateTime startTime;   // set when guard verifies OTP → ACTIVE
//     private LocalDateTime endTime;     // startTime + durationDays
//     private LocalDateTime exitTime;    // set when EXPIRED
 
//     // ── Guard info (set on activation) ────────────────────────────────────
//     private String verifiedByGuardId;
//     private String verifiedByGuardName;
//     private String entryGate;
 
//     @PrePersist
//     protected void onCreate() {
//         if (requestedAt == null) requestedAt = LocalDateTime.now();
//         if (status == null)      status      = GuestParkingStatus.PENDING;
//     }
// }
 
 
// package com.bsgated.model;

// import jakarta.persistence.*;
// import lombok.Data;
// import lombok.NoArgsConstructor;
// import lombok.AllArgsConstructor;

// import java.time.LocalDate;
// import java.time.LocalDateTime;

// /**
//  * GuestParking entity — maps to guest_parking table.
//  *
//  * New columns vs previous version:
//  *   expected_date  DATE        — the date the guest is expected (chosen by resident)
//  *   slot_number    VARCHAR(10) — e.g. "A3", "B12" (chosen by resident from slot picker)
//  *   parking_otp    VARCHAR(6)  — 6-digit OTP generated by the backend on create
//  */
// @Entity
// @Table(name = "guest_parking")
// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// public class GuestParking {

//     @Id
//     @GeneratedValue(strategy = GenerationType.UUID)
//     private String id;

//     // ── Resident / host ────────────────────────────────────────────────────────
//     @Column(name = "resident_id",   nullable = false)
//     private String residentId;

//     @Column(name = "resident_name")
//     private String residentName;

//     @Column(name = "unit")
//     private String unit;

//     // ── Guest details ──────────────────────────────────────────────────────────
//     @Column(name = "guest_name",  nullable = false)
//     private String guestName;

//     @Column(name = "guest_phone")
//     private String guestPhone;

//     // ── Vehicle ────────────────────────────────────────────────────────────────
//     @Column(name = "vehicle_number", nullable = false)
//     private String vehicleNumber;

//     @Column(name = "vehicle_type")
//     private String vehicleType;

//     // ── Parking slot & timing ─────────────────────────────────────────────────
//     /**
//      * The date the guest is expected — used for slot-availability checks.
//      * Stored as DATE (no time zone issues).
//      */
//     @Column(name = "expected_date", nullable = false)
//     private LocalDate expectedDate;

//     /** Duration in days, stored as a string ("1","2","3","7"). */
//     @Column(name = "duration")
//     private String duration;

//     /**
//      * The specific slot chosen by the resident — e.g. "A3", "B12".
//      * The service layer verifies this slot is free before saving.
//      */
//     @Column(name = "slot_number", nullable = false, length = 10)
//     private String slotNumber;

//     // ── OTP & status ──────────────────────────────────────────────────────────
//     @Column(name = "parking_otp", length = 6)
//     private String parkingOtp;

//     @Enumerated(EnumType.STRING)
//     @Column(name = "status", nullable = false)
//     private GuestParkingStatus status = GuestParkingStatus.PENDING;

//     // ── Timestamps ─────────────────────────────────────────────────────────────
//     @Column(name = "requested_at")
//     private LocalDateTime requestedAt;

//     /** Set when guard verifies OTP and marks ACTIVE */
//     @Column(name = "start_time")
//     private LocalDateTime startTime;

//     /** Calculated as startTime + duration days when activated */
//     @Column(name = "end_time")
//     private LocalDateTime endTime;
// }


package com.bsgated.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Entity
@Table(name = "guest_parking")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GuestParking {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    // ───────────────── RESIDENT ─────────────────

    @Column(name = "resident_id", nullable = false)
    private String residentId;

    @Column(name = "resident_name")
    private String residentName;

    @Column(name = "unit")
    private String unit;

    // ───────────────── GUEST ─────────────────

    @Column(name = "guest_name", nullable = false)
    private String guestName;

    @Column(name = "guest_phone")
    private String guestPhone;

    // ───────────────── VEHICLE ─────────────────

    @Column(name = "vehicle_number", nullable = false)
    private String vehicleNumber;

    @Column(name = "vehicle_type")
    private String vehicleType;

    // ───────────────── PARKING ─────────────────

    @Column(name = "expected_date")
    private String expectedDate;

    @Column(name = "duration_days")
    private Integer durationDays;

    @Column(name = "slot_number")
    private String slotNumber;

    @Column(name = "parking_otp", length = 6)
    private String parkingOtp;

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    @Builder.Default
    private GuestParkingStatus status =
            GuestParkingStatus.PENDING;

    // ───────────────── TIME ─────────────────

    @Column(name = "requested_at")
    @Builder.Default
    private LocalDateTime requestedAt =
            LocalDateTime.now();

    @Column(name = "approved_at")
    private LocalDateTime approvedAt;

    @Column(name = "rejected_at")
    private LocalDateTime rejectedAt;

    @Column(name = "start_time")
    private LocalDateTime startTime;

    @Column(name = "end_time")
    private LocalDateTime endTime;

    @Column(name = "exit_time")
    private LocalDateTime exitTime;

    // ───────────────── GUARD ─────────────────

    @Column(name = "entry_gate")
    private String entryGate;

    @Column(name = "verified_by_guard_id")
    private String verifiedByGuardId;

    @Column(name = "verified_by_guard_name")
    private String verifiedByGuardName;

        // ───────────────── getter and setters ─────────────────

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getResidentId() {
        return residentId;
    }

    public void setResidentId(String residentId) {
        this.residentId = residentId;
    }

    public String getResidentName() {
        return residentName;
    }

    public void setResidentName(String residentName) {
        this.residentName = residentName;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getGuestName() {
        return guestName;
    }

    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }

    public String getGuestPhone() {
        return guestPhone;
    }

    public void setGuestPhone(String guestPhone) {
        this.guestPhone = guestPhone;
    }

    public String getVehicleNumber() {
        return vehicleNumber;
    }

    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    public String getExpectedDate() {
        return expectedDate;
    }

    public void setExpectedDate(String expectedDate) {
        this.expectedDate = expectedDate;
    }

    public Integer getDurationDays() {
        return durationDays;
    }

    public void setDurationDays(Integer durationDays) {
        this.durationDays = durationDays;
    }

    public String getSlotNumber() {
        return slotNumber;
    }

    public void setSlotNumber(String slotNumber) {
        this.slotNumber = slotNumber;
    }

    public String getParkingOtp() {
        return parkingOtp;
    }

    public void setParkingOtp(String parkingOtp) {
        this.parkingOtp = parkingOtp;
    }

    public GuestParkingStatus getStatus() {
        return status;
    }

    public void setStatus(GuestParkingStatus status) {
        this.status = status;
    }

    public LocalDateTime getRequestedAt() {
        return requestedAt;
    }

    public void setRequestedAt(LocalDateTime requestedAt) {
        this.requestedAt = requestedAt;
    }

    public LocalDateTime getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(LocalDateTime approvedAt) {
        this.approvedAt = approvedAt;
    }

    public LocalDateTime getRejectedAt() {
        return rejectedAt;
    }

    public void setRejectedAt(LocalDateTime rejectedAt) {
        this.rejectedAt = rejectedAt;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public LocalDateTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    public LocalDateTime getExitTime() {
        return exitTime;
    }

    public void setExitTime(LocalDateTime exitTime) {
        this.exitTime = exitTime;
    }

    public String getEntryGate() {
        return entryGate;
    }

    public void setEntryGate(String entryGate) {
        this.entryGate = entryGate;
    }

    public String getVerifiedByGuardId() {
        return verifiedByGuardId;
    }

    public void setVerifiedByGuardId(String verifiedByGuardId) {
        this.verifiedByGuardId = verifiedByGuardId;
    }

    public String getVerifiedByGuardName() {
        return verifiedByGuardName;
    }

    public void setVerifiedByGuardName(String verifiedByGuardName) {
        this.verifiedByGuardName = verifiedByGuardName;
    }



    
}