package com.bsgated.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Lifecycle statuses:
 *
 * submitted               → resident submitted, admin must assign vendor
 * vendor_assigned         → admin assigned a vendor
 * quote_submitted         → vendor submitted quote (rate + description)
 * quote_forwarded         → admin forwarded quote to resident
 * quote_accepted          → resident accepted
 * quote_rejected          → resident rejected — admin will re-assign
 * gate_otp_generated      → admin generated OTP; vendor heading to gate
 * work_started            → guard verified OTP; vendor on site
 * work_completed          → vendor marked work done
 * payment_requested       → vendor raised payment request to admin
 * payment_sent_to_resident→ admin forwarded payment request to resident
 * payment_done            → resident paid via Razorpay
 * closed                  → admin confirmed payment to vendor, job closed
 */
@Entity
@Table(name = "maintenance_requests")
public class MaintenanceRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── Resident info ──────────────────────────────────────────────────
    private String residentId;
    private String residentName;
    private String residentPhone;
    private String unit;

    // ── Request details ────────────────────────────────────────────────
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    private String category;
    private String priority;         // Low | Medium | High | Urgent
    private String preferredSlot;
    private String contactPref;

    // ── Status ────────────────────────────────────────────────────────
    @Column(nullable = false)
    private String status = "submitted";

    // ── Vendor info (set when admin assigns) ──────────────────────────
    private Long   vendorId;
    private String vendorName;
    private String vendorPhone;

    // ── Quote (submitted by vendor) ────────────────────────────────────
    private Double  quoteAmount;
    @Column(columnDefinition = "TEXT")
    private String  quoteDescription;
    private Integer quoteEstimatedDays;

    // ── Gate OTP (generated by admin after quote accepted) ─────────────
    private String gateOtp;
    private LocalDateTime gateOtpGeneratedAt;
    private boolean gateOtpUsed = false;
    private String  gateVerifiedBy;    // guardId — guardName
    private LocalDateTime gateVerifiedAt;

    // ── Work stages ────────────────────────────────────────────────────
    private LocalDateTime workStartedAt;
    private LocalDateTime workCompletedAt;

    // ── Payment ────────────────────────────────────────────────────────
    private Double  paymentAmount;
    @Column(columnDefinition = "TEXT")
    private String  paymentNotes;
    private String  razorpayOrderId;
    private String  razorpayPaymentId;

    private Integer rating;
    @Column(columnDefinition = "TEXT")
    private String review;
    @Column(columnDefinition = "TEXT")
    private String tags;

    // ── Admin fields ───────────────────────────────────────────────────
    private Long   adminId;
    private String adminName;

    // ── Rejection ─────────────────────────────────────────────────────
    @Column(columnDefinition = "TEXT")
    private String rejectionReason;

    // ── Timestamps ────────────────────────────────────────────────────
    private LocalDateTime createdAt  = LocalDateTime.now();
    private LocalDateTime updatedAt  = LocalDateTime.now();

    // ── Timeline stored as JSON text ──────────────────────────────────
    @Column(columnDefinition = "TEXT")
    private String timelineJson = "[]";

    // ─── Getters & Setters ────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getResidentId() { return residentId; }
    public void setResidentId(String r) { this.residentId = r; }

    public String getResidentName() { return residentName; }
    public void setResidentName(String r) { this.residentName = r; }

    public String getResidentPhone() { return residentPhone; }
    public void setResidentPhone(String r) { this.residentPhone = r; }

    public String getUnit() { return unit; }
    public void setUnit(String u) { this.unit = u; }

    public String getTitle() { return title; }
    public void setTitle(String t) { this.title = t; }

    public String getDescription() { return description; }
    public void setDescription(String d) { this.description = d; }

    public String getCategory() { return category; }
    public void setCategory(String c) { this.category = c; }

    public String getPriority() { return priority; }
    public void setPriority(String p) { this.priority = p; }

    public String getPreferredSlot() { return preferredSlot; }
    public void setPreferredSlot(String s) { this.preferredSlot = s; }

    public String getContactPref() { return contactPref; }
    public void setContactPref(String c) { this.contactPref = c; }

    public String getStatus() { return status; }
    public void setStatus(String s) { this.status = s; }

    public Long getVendorId() { return vendorId; }
    public void setVendorId(Long v) { this.vendorId = v; }

    public String getVendorName() { return vendorName; }
    public void setVendorName(String v) { this.vendorName = v; }

    public String getVendorPhone() { return vendorPhone; }
    public void setVendorPhone(String v) { this.vendorPhone = v; }

    public Double getQuoteAmount() { return quoteAmount; }
    public void setQuoteAmount(Double q) { this.quoteAmount = q; }

    public String getQuoteDescription() { return quoteDescription; }
    public void setQuoteDescription(String q) { this.quoteDescription = q; }

    public Integer getQuoteEstimatedDays() { return quoteEstimatedDays; }
    public void setQuoteEstimatedDays(Integer q) { this.quoteEstimatedDays = q; }

    public String getGateOtp() { return gateOtp; }
    public void setGateOtp(String g) { this.gateOtp = g; }

    public LocalDateTime getGateOtpGeneratedAt() { return gateOtpGeneratedAt; }
    public void setGateOtpGeneratedAt(LocalDateTime t) { this.gateOtpGeneratedAt = t; }

    public boolean isGateOtpUsed() { return gateOtpUsed; }
    public void setGateOtpUsed(boolean b) { this.gateOtpUsed = b; }

    public String getGateVerifiedBy() { return gateVerifiedBy; }
    public void setGateVerifiedBy(String g) { this.gateVerifiedBy = g; }

    public LocalDateTime getGateVerifiedAt() { return gateVerifiedAt; }
    public void setGateVerifiedAt(LocalDateTime t) { this.gateVerifiedAt = t; }

    public LocalDateTime getWorkStartedAt() { return workStartedAt; }
    public void setWorkStartedAt(LocalDateTime t) { this.workStartedAt = t; }

    public LocalDateTime getWorkCompletedAt() { return workCompletedAt; }
    public void setWorkCompletedAt(LocalDateTime t) { this.workCompletedAt = t; }

    public Double getPaymentAmount() { return paymentAmount; }
    public void setPaymentAmount(Double p) { this.paymentAmount = p; }

    public String getPaymentNotes() { return paymentNotes; }
    public void setPaymentNotes(String p) { this.paymentNotes = p; }

    public String getRazorpayOrderId() { return razorpayOrderId; }
    public void setRazorpayOrderId(String r) { this.razorpayOrderId = r; }

    public String getRazorpayPaymentId() { return razorpayPaymentId; }
    public void setRazorpayPaymentId(String r) { this.razorpayPaymentId = r; }

    public Integer getRating() { return rating; }
    public void setRating(Integer r) { this.rating = r; }

    public String getReview() { return review; }
    public void setReview(String r) { this.review = r; }

    public String getTags() { return tags; }
    public void setTags(String t) { this.tags = t; }

    public Long getAdminId() { return adminId; }
    public void setAdminId(Long a) { this.adminId = a; }

    public String getAdminName() { return adminName; }
    public void setAdminName(String a) { this.adminName = a; }

    public String getRejectionReason() { return rejectionReason; }
    public void setRejectionReason(String r) { this.rejectionReason = r; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime t) { this.createdAt = t; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime t) { this.updatedAt = t; }

    public String getTimelineJson() { return timelineJson; }
    public void setTimelineJson(String t) { this.timelineJson = t; }
}
